// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// timesTwo
NumericVector timesTwo(NumericVector x);
RcppExport SEXP bacollite_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwo(x));
    return rcpp_result_gen;
END_RCPP
}
// helloWorld
CharacterVector helloWorld();
RcppExport SEXP bacollite_helloWorld() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(helloWorld());
    return rcpp_result_gen;
END_RCPP
}
// helloPerson
CharacterVector helloPerson(CharacterVector cvname);
RcppExport SEXP bacollite_helloPerson(SEXP cvnameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type cvname(cvnameSEXP);
    rcpp_result_gen = Rcpp::wrap(helloPerson(cvname));
    return rcpp_result_gen;
END_RCPP
}
// helloNvec
NumericVector helloNvec(CharacterVector cvname);
RcppExport SEXP bacollite_helloNvec(SEXP cvnameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type cvname(cvnameSEXP);
    rcpp_result_gen = Rcpp::wrap(helloNvec(cvname));
    return rcpp_result_gen;
END_RCPP
}
// helloDfram
DataFrame helloDfram(CharacterVector cvname);
RcppExport SEXP bacollite_helloDfram(SEXP cvnameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type cvname(cvnameSEXP);
    rcpp_result_gen = Rcpp::wrap(helloDfram(cvname));
    return rcpp_result_gen;
END_RCPP
}
// helloIso
DataFrame helloIso(CharacterVector cvseq);
RcppExport SEXP bacollite_helloIso(SEXP cvseqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type cvseq(cvseqSEXP);
    rcpp_result_gen = Rcpp::wrap(helloIso(cvseq));
    return rcpp_result_gen;
END_RCPP
}
