# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppIso <- function(cvseq) {
    .Call('_bacollite_cppIso', PACKAGE = 'bacollite', cvseq)
}

cppIsoAtom <- function(nC, nH, nN, nO, nS) {
    .Call('_bacollite_cppIsoAtom', PACKAGE = 'bacollite', nC, nH, nN, nO, nS)
}

cppIsoAtom_p <- function(Ratoms) {
    .Call('_bacollite_cppIsoAtom_p', PACKAGE = 'bacollite', Ratoms)
}

aa_seq_to_atoms <- function(cvseq) {
    .Call('_bacollite_aa_seq_to_atoms', PACKAGE = 'bacollite', cvseq)
}

