# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply a number by two
#'
#' @param x the number that you want to multiply by 2
#' @export
timesTwo <- function(x) {
    .Call('bacollite_timesTwo', PACKAGE = 'bacollite', x)
}

cppIso <- function(cvseq) {
    .Call('bacollite_cppIso', PACKAGE = 'bacollite', cvseq)
}

