# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply a number by two
#'
#' @param x the number that you want to multiply by 2
#' @export
timesTwo <- function(x) {
    .Call('bacollite_timesTwo', PACKAGE = 'bacollite', x)
}

helloWorld <- function() {
    .Call('bacollite_helloWorld', PACKAGE = 'bacollite')
}

helloPerson <- function(cvname) {
    .Call('bacollite_helloPerson', PACKAGE = 'bacollite', cvname)
}

helloNvec <- function(cvname) {
    .Call('bacollite_helloNvec', PACKAGE = 'bacollite', cvname)
}

helloDfram <- function(cvname) {
    .Call('bacollite_helloDfram', PACKAGE = 'bacollite', cvname)
}

helloIso <- function(cvseq) {
    .Call('bacollite_helloIso', PACKAGE = 'bacollite', cvseq)
}

